// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetSuiteRAG.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NetSuiteRAG.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251011185748_AddBusinessGlossary")]
    partial class AddBusinessGlossary
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NetSuiteRAG.Shared.Models.CustomFieldChangeLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChangeDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("change_description");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("change_type");

                    b.Property<Guid>("CustomFieldDescriptorId")
                        .HasColumnType("uuid")
                        .HasColumnName("custom_field_descriptor_id");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<string>("FieldId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("field_id");

                    b.Property<string>("NewValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_value");

                    b.HasKey("Id");

                    b.HasIndex("ChangeType")
                        .HasDatabaseName("ix_custom_field_change_logs_change_type");

                    b.HasIndex("CustomFieldDescriptorId")
                        .HasDatabaseName("ix_custom_field_change_logs_descriptor_id");

                    b.HasIndex("DetectedAt")
                        .HasDatabaseName("ix_custom_field_change_logs_detected_at");

                    b.HasIndex("FieldId")
                        .HasDatabaseName("ix_custom_field_change_logs_field_id");

                    b.ToTable("custom_field_change_logs", (string)null);
                });

            modelBuilder.Entity("NetSuiteRAG.Shared.Models.CustomFieldDescriptor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Aliases")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("aliases");

                    b.Property<decimal?>("AmbiguityScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("ambiguity_score");

                    b.Property<string>("BusinessContext")
                        .HasColumnType("jsonb")
                        .HasColumnName("business_context");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("default_value");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EnrichedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enriched_at");

                    b.Property<string>("FieldId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("field_id");

                    b.Property<bool>("IsMandatory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_mandatory");

                    b.Property<bool>("IsStale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_stale");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("label");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<string>("RecordType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("record_type");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EnrichedAt")
                        .HasDatabaseName("ix_custom_field_descriptors_enriched_at");

                    b.HasIndex("IsStale")
                        .HasDatabaseName("ix_custom_field_descriptors_is_stale");

                    b.HasIndex("Label")
                        .HasDatabaseName("ix_custom_field_descriptors_label");

                    b.HasIndex("LastSeenAt")
                        .HasDatabaseName("ix_custom_field_descriptors_last_seen_at");

                    b.HasIndex("RecordType")
                        .HasDatabaseName("ix_custom_field_descriptors_record_type");

                    b.HasIndex("RecordType", "FieldId")
                        .IsUnique()
                        .HasDatabaseName("ix_custom_field_descriptors_record_type_field_id");

                    b.ToTable("custom_field_descriptors", (string)null);
                });

            modelBuilder.Entity("NetSuiteRAG.Shared.Models.FieldDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Aliases")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("aliases");

                    b.Property<decimal?>("AmbiguityScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("ambiguity_score");

                    b.Property<string>("BusinessContext")
                        .HasColumnType("jsonb")
                        .HasColumnName("business_context");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EnrichedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enriched_at");

                    b.Property<string>("FieldId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("field_id");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("field_type");

                    b.Property<bool>("IsCustomField")
                        .HasColumnType("boolean")
                        .HasColumnName("is_custom_field");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("label");

                    b.Property<string>("RecordType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("record_type");

                    b.Property<string>("RequiredJoin")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("required_join");

                    b.Property<string>("SchemaUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("schema_url");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source");

                    b.Property<bool>("SupportsColumn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("supports_column");

                    b.Property<bool>("SupportsFilter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("supports_filter");

                    b.Property<bool>("SupportsSummary")
                        .HasColumnType("boolean")
                        .HasColumnName("supports_summary");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("ValidOperators")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("valid_operators");

                    b.HasKey("Id");

                    b.HasIndex("EnrichedAt")
                        .HasDatabaseName("ix_field_definitions_enriched_at");

                    b.HasIndex("IsCustomField")
                        .HasDatabaseName("ix_field_definitions_is_custom_field");

                    b.HasIndex("Label")
                        .HasDatabaseName("ix_field_definitions_label");

                    b.HasIndex("RecordType")
                        .HasDatabaseName("ix_field_definitions_record_type");

                    b.HasIndex("RequiredJoin")
                        .HasDatabaseName("ix_field_definitions_required_join");

                    b.HasIndex("RecordType", "FieldId")
                        .IsUnique()
                        .HasDatabaseName("ix_field_definitions_record_type_field_id");

                    b.ToTable("field_definitions", (string)null);
                });

            modelBuilder.Entity("NetSuiteRAG.Shared.Models.GlossaryTerm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("definition");

                    b.Property<DateTime?>("EmbeddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("embedded_at");

                    b.Property<string>("EmbeddingJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("embedding_json");

                    b.Property<string>("Examples")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("examples");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<string>("Synonyms")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("synonyms");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("term");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_glossary_terms_category");

                    b.HasIndex("EmbeddedAt")
                        .HasDatabaseName("ix_glossary_terms_embedded_at");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_glossary_terms_is_active");

                    b.HasIndex("Term")
                        .HasDatabaseName("ix_glossary_terms_term");

                    b.ToTable("glossary_terms", (string)null);
                });

            modelBuilder.Entity("NetSuiteRAG.Shared.Models.QueryExemplar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("difficulty");

                    b.Property<DateTime?>("EmbeddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("embedded_at");

                    b.Property<string>("EmbeddingJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("embedding_json");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("explanation");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastRetrievedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_retrieved_at");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<string>("NaturalQuery")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("natural_query");

                    b.Property<string>("RecordType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("record_type");

                    b.Property<int>("RetrievalCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retrieval_count");

                    b.Property<string>("SavedSearchPlanJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("saved_search_plan_json");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("tags");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Difficulty")
                        .HasDatabaseName("ix_query_exemplars_difficulty");

                    b.HasIndex("EmbeddedAt")
                        .HasDatabaseName("ix_query_exemplars_embedded_at");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_query_exemplars_is_active");

                    b.HasIndex("RecordType")
                        .HasDatabaseName("ix_query_exemplars_record_type");

                    b.HasIndex("RetrievalCount")
                        .HasDatabaseName("ix_query_exemplars_retrieval_count");

                    b.ToTable("query_exemplars", (string)null);
                });

            modelBuilder.Entity("NetSuiteRAG.Shared.Models.CustomFieldChangeLog", b =>
                {
                    b.HasOne("NetSuiteRAG.Shared.Models.CustomFieldDescriptor", "CustomFieldDescriptor")
                        .WithMany()
                        .HasForeignKey("CustomFieldDescriptorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomFieldDescriptor");
                });
#pragma warning restore 612, 618
        }
    }
}
