using System.Text.Json.Serialization;

namespace NetSuiteRAG.Shared.Models;

/// <summary>
/// Represents a complete NetSuite Saved Search plan generated by the LLM.
/// This is the core data structure that defines what data to retrieve and how to display it.
/// The plan is validated through a 5-layer validation pipeline before execution.
/// </summary>
public class SavedSearchPlan
{
    /// <summary>
    /// The NetSuite record type to search (e.g., "transaction", "customer", "item").
    /// Must be a valid NetSuite record type.
    /// Required.
    /// </summary>
    [JsonPropertyName("recordType")]
    public required string RecordType { get; init; }

    /// <summary>
    /// List of filter conditions to apply to the search.
    /// Filters determine which records are included in the results.
    /// At least one filter is recommended for performance.
    /// Required (but can be empty list).
    /// </summary>
    [JsonPropertyName("filters")]
    public required List<Filter> Filters { get; init; }

    /// <summary>
    /// List of columns to display in the search results.
    /// Columns determine which fields are included in the result set.
    /// At least one column is required.
    /// Required.
    /// </summary>
    [JsonPropertyName("columns")]
    public required List<Column> Columns { get; init; }

    /// <summary>
    /// Optional: List of sort orders to apply to the results.
    /// Sorts determine the order in which records are returned.
    /// If not specified, results are returned in NetSuite's default order.
    /// </summary>
    [JsonPropertyName("sorts")]
    public List<Sort>? Sorts { get; init; }

    /// <summary>
    /// Optional: Ambiguous field values requiring user disambiguation.
    /// When present, the search cannot be executed until the user selects
    /// specific values for the ambiguous fields.
    /// Returns HTTP 409 Conflict with disambiguation options.
    /// </summary>
    [JsonPropertyName("ambiguous")]
    public AmbiguousFields? Ambiguous { get; init; }

    /// <summary>
    /// Optional: Title for this search.
    /// Used for display purposes in the UI and search history.
    /// </summary>
    [JsonPropertyName("title")]
    public string? Title { get; init; }

    /// <summary>
    /// Optional: Description of what this search retrieves.
    /// Helps users understand the purpose of the search.
    /// </summary>
    [JsonPropertyName("description")]
    public string? Description { get; init; }

    /// <summary>
    /// Optional: Maximum number of rows to return.
    /// Used for result set limiting and performance control.
    /// If not specified, all matching records are returned.
    /// </summary>
    [JsonPropertyName("maxResults")]
    public int? MaxResults { get; init; }
}
